- dataSource: AssetsConfigDataSource
  type: Mutation
  field: updateSiteConfiguration
  kind: PIPELINE
  functions:
    - validateResources
    - updateSiteConfiguration
  request: admin/siteConfiguration.update.request.vtl
  response: admin/siteConfiguration.update.response.vtl
