org: drmollineda
app: e-signatures-sls-test
service: digital-petitions-backend

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, "us-east-1"}
  stage: ${opt:stage, "dev"}

functions:
  sample:
    handler: src/functions/sample.default

  echo:
    handler: src/functions/echo.default

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local
  - serverless-appsync-plugin
  - serverless-appsync-simulator
  - serverless-offline

resources:
  - ${file(src/resources/data.yml)}
  - ${file(src/resources/auth.yml)}

custom:
  # configure TS compilation using esbuild
  esbuild:
    watch:
      pattern: ['src/**/*.ts']

  # use a local in-memory database for testing
  dynamodb:
    stages:
      - dev
    start:
      inMemory: true
      migrate: true

  # Simulate AppSync for local development
  appsync-simulator:
    apiKey: da2-fakeApiId123456
  
  # setup AppSync-related data
  appSync:
    name: ${self:provider.stage}-digital-petitions-api
    schema: src/schema/schema.graphql

    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: { Ref: AWS::Region }
      defaultAction: DENY
      userPoolId: { Ref: UserPool }

    dataSources:
      - type: AMAZON_DYNAMODB
        name: DynamoDBDataSource
        
        config:
          tableName: { Ref: DynamoDBTable }
          iamRoleStatements:
            - Effect: Allow
              Action:
                - "dynamodb:GetItem"
                - "dynamodb:PutItem"
                - "dynamodb:DeleteItem"
                - "dynamodb:Query"
              Resource:
                - { Fn::GetAtt: [DynamoDBTable, Arn] }
                - { Fn::Join: ['', [{ Fn::GetAtt: [DynamoDBTable, Arn] }, "/*"]] }

      - type: AWS_LAMBDA
        name: EchoDebugLambdaDataSource

        config:
          functionName: echo

    mappingTemplatesLocation: src/templates

    mappingTemplates:
      - dataSource: EchoDebugLambdaDataSource
        type: Mutation
        field: point
      - dataSource: EchoDebugLambdaDataSource
        type: Query
        field: points
