services:
  backend-auth:
    path: auth

  backend-api:
    path: api
    params:
      userPoolId: ${backend-auth.userPoolId}
      userPoolClientId: ${backend-auth.userPoolClientId}
      petitionTableArn: ${backend-data.petitionTableArn}
      petitionTableName: ${backend-data.petitionTableName}
      signatureTableArn: ${backend-data.signatureTableArn}
      signatureTableName: ${backend-data.signatureTableName}
      siteConfigTableArn: ${backend-data.siteConfigTableArn}
      siteConfigTableName: ${backend-data.siteConfigTableName}
      adminLambdaArn: ${backend-auth.adminLambdaArn}
      assetsLambdaArn: ${frontend-assets.assetsLambdaArn}
      assetsBucketName: ${frontend-assets.assetsBucketName}
      signatureVerificationLambdaArn: ${backend-signature-validation.signatureValidationLambdaArn}

  backend-mail:
    path: mail

  backend-auth-public:
    path: auth-public
    params:
      apiId: ${backend-api.apiId}
      userPoolClientId: ${backend-auth.userPoolClientId}
      userPoolProviderName: ${backend-auth.userPoolProviderName}

  backend-signature-validation:
    path: validation
    params: 
      identity: ${backend-mail.mailingIdentity}

  backend-data:
    path: data

  frontend-assets:
    path: assets

  frontend:
    path: frontend
    params:
      assetsBucketName: ${frontend-assets.assetsBucketName}
      assetsBucketId: ${frontend-assets.assetsBucketId}
      assetsBucketDomain: ${frontend-assets.assetsBucketDomain}
      userPoolId: ${backend-auth.userPoolId}
      userPoolClientId: ${backend-auth.userPoolClientId}
      apiEndpoint: ${backend-api.apiEndpoint}
