org: drmollineda
app: e-signatures-sls-test
service: digital-petitions-backend

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: src/functions/handler.hello

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
