services:
  backend-auth:
    path: auth

  backend-api:
    path: api
    dependsOn: backend-auth

  backend-auth-public:
    path: auth-public
    dependsOn: 
      - backend-api
      - backend-auth
