services:
  backend-auth:
    path: auth

  backend-api:
    path: api
    params:
      userPoolId: ${backend-auth.userPoolId}
      petitionTableArn: ${backend-data.petitionTableArn}
      petitionTableName: ${backend-data.petitionTableName}
      adminLambdaArn: ${backend-auth.adminLambdaArn}

  backend-auth-public:
    path: auth-public
    params:
      apiId: ${backend-api.apiId}
      userPoolClientId: ${backend-auth.userPoolClientId}
      userPoolProviderName: ${backend-auth.userPoolProviderName}

  backend-data:
    path: data

  frontend:
    path: frontend
    params:
      userPoolId: ${backend-auth.userPoolId}
      userPoolClientId: ${backend-auth.userPoolClientId}
      apiEndpoint: ${backend-api.apiEndpoint}
