org: drmollineda
app: e-signatures-sls-test
service: digital-petitions-backend

frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: functions/handler.hello
