Resources:
  # The user pool used to provide authenticated
  # users
  CognitoUserPoolAppUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: ${self:provider.stage}-UserPool
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: "verified_email"
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - "email"
      Schema:
        - Name: "address"
          AttributeDataType: "String"
          Mutable: true
          Required: true
        - Name: "given_name"
          AttributeDataType: "String"
          Mutable: true
          Required: true
        - Name: "family_name"
          AttributeDataType: "String"
          Mutable: true
          Required: true
        - Name: "email"
          AttributeDataType: "String"
          Mutable: true
          Required: true
        - Name: "access_group"
          AttributeDataType: "String"
          Mutable: true
          Required: false
      AliasAttributes:
        - "email"
