schema:
 - "directive @aws_cognito_user_pools(cognito_groups: [String!]) on FIELD_DEFINITION|OBJECT"
 - "directive @aws_iam on FIELD_DEFINITION|OBJECT"
 - "scalar AWSDateTime"
 - "./schema/**/*.graphql"
