app: e-signatures
org: maplighttech
service: backend-api

frameworkVersion: '3'

functions:
  echo:
    handler: lambda/echo/index.handler

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, "dev"}

custom:
  myUserPoolId: ${param:userPoolId, output:backend-auth.UserPoolId}
  myPetitionTableName: ${param:petitionTableName, output:backend-data.PetitionsTableName}
  myPetitionTableArn: ${param:petitionTableArn, output:backend-data.PetitionsTableArn}
  mySignatureTableName: ${param:signatureTableName, output:backend-data.SignaturesTableName}
  mySignatureTableArn: ${param:signatureTableArn, output:backend-data.SignaturesTableArn}
  myAdminLambdaArn: ${param:adminLambdaArn, output:backend-auth.AdminLambdaArn}

  esbuild:
    minify: true
    watch:
      pattern: ["lambda/**/*.ts"]
      ignore: ["./serverles/**/*", ".build"]

  appSync:
    name: ${self:provider.stage}-ESignaturesAPI

    schema: "./schema/**/*.graphql"

    logConfig:
      level: ERROR

    authenticationType: AWS_IAM

    additionalAuthenticationProviders:
      - authenticationType: AMAZON_COGNITO_USER_POOLS
        userPoolConfig:
          userPoolId: ${self:custom.myUserPoolId}

    mappingTemplatesLocation: templates
    defaultMappingTemplates:
      request: echo.request.vtl
      response: echo.response.vtl

    substitutions:
      DEFAULT_PAGE_SIZE: 10

      # petition status values
      STATUS_NEW: "A1"
      STATUS_CANCELED: "A2"
      STATUS_WITHDRAWN: "A3"
      STATUS_REJECTED: "A4"
      STATUS_NOT_QUALIFIED: "B1"
      STATUS_QUALIFIED: "B2"
      STATUS_ACTIVE: "C1"

      # petition status bounds for range queries
      STATUS_INACTIVE_PUBLIC_LOWER_BOUND: "B"
      STATUS_INACTIVE_UPPER_BOUND: "C"
      STATUS_INACTIVE_LOWER_BOUND: "A2"

      # signature status values
      SIGNATURE_SUBMITTED: "A1"
      SIGNATURE_VERIFIED: "A2"
      SIGNATURE_APPROVED: "A3"
      SIGNATURE_REJECTED: "A4"

      # user lambda request arguments mapping
      USER_PETITIONER: "petitioner"
      USER_GUEST: "city_staff_guest"
      USER_STAFF: "city_staff"
      USER_ADMIN: "admin"
      USER_NONE: "none"

      COGNITO_USER_POOL: ${self:custom.myUserPoolId}

    mappingTemplates:
      - ${file(./templates/echo.yml)}
      - ${file(./templates/petitioner/submitPetition.issue.yml)}
      - ${file(./templates/petitioner/editPetition.issue.yml)}
      - ${file(./templates/petitioner/submitPetition.candidate.yml)}
      - ${file(./templates/petitioner/editPetition.candidate.yml)}
      - ${file(./templates/staff/approvePetition.yml)}
      - ${file(./templates/staff/rejectPetition.yml)}
      - ${file(./templates/staff/createUser.yml)}
      - ${file(./templates/staff/deleteUser.yml)}
      - ${file(./templates/staff/selectUser.yml)}
      - ${file(./templates/staff/updateUserAccess.yml)}
      - ${file(./templates/listPetition.byType.yml)}
      - ${file(./templates/listPetition.byOwner.yml)}
      - ${file(./templates/petition.byId.yml)}
      - ${file(./templates/signatures.byPetition.yml)}

    dataSources:
      - ${file(./data/petitions.yml)}
      - ${file(./data/echo.yml)}
      - ${file(./data/signatures.yml)}
      - ${file(./data/users.yml)}

    xrayEnabled: true
    # wafConfig:
    #   rules:
    #     - throttle: 100
    #     - disableIntrospection

plugins:
  - serverless-appsync-plugin
  - serverless-esbuild

resources:
  Outputs:
    apiId: { Value: { Ref: GraphQlApi } }
    apiEndpoint: { Value: { Fn::GetAtt: [GraphQlApi, GraphQLUrl] } }

outputs:
  ApiId: { Ref: GraphQlApi }
  ApiEndpoint: { Fn::GetAtt: [GraphQlApi, GraphQLUrl] }
