app: e-signatures
org: maplighttech
service: backend-api

frameworkVersion: '3'

functions:
  echo:
    handler: lambda/echo/index.handler

custom:
  esbuild:
    minify: true
    watch:
      pattern: ["lambda/**/*.ts"]
      ignore: ["./serverles/**/*", ".build"]

  appSync:
    name: ${self.provider.stage}-ESignaturesAPI

    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      defaultAction: ALLOW
      userPoolId: ${output:backend-auth.UserPoolId}

    additionalAuthenticationProviders:
      - authenticationType: AWS_IAM

    mappingTemplatesLocation: templates
    defaultMappingTemplates:
      request: echo.request.vtl
      response: echo.response.vtl

    mappingTemplates:
      - dataSource: EchoDataSource
        type: Query
        field: publicType
      - dataSource: EchoDataSource
        type: Query
        field: adminType
      - dataSource: EchoDataSource
        type: Query
        field: petitionerType

    dataSources:
      - type: AWS_LAMBDA
        name: EchoDataSource
        description: "A simple lambda datasource for testing"
        config:
          functionName: echo

    xrayEnabled: true
    # wafConfig:
    #   enabled: true
    #   name: AppSyncWafConfig
    #   defaultAction: Allow
    #   rules:
    #     - throttle: 100
    #     - disableIntrospection

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, "dev"}

plugins:
  - serverless-appsync-plugin
  - serverless-esbuild
